FROM python:3.12.1-slim

RUN pip install streamlit pandas pyarrow

COPY ./app.py /app/app.py

WORKDIR /app

ENTRYPOINT [ "streamlit", "run", "app.py" ]


# FROM python:3.10-slim

# WORKDIR /app

# COPY requirements.txt requirements.txt
# RUN pip install -r requirements.txt

# COPY . .

# CMD ["streamlit", "run", "app.py"]